#PS1
PROMPT="%~ $(tput setaf 7)> "
#BULLSHIT
CASE_SENSITIVE="false"
ENABLE_CORRECTION="false"
#COMPLETION_WAITING_DOTS="true"
plugins=(git command-time zsh-syntax-highlighting)
ZSH_COMMAND_TIME_MIN_SECONDS=1
ZSH_COMMAND_TIME_MSG="%s"
ZSH_COMMAND_TIME_COLOR="white"
ZSH_COMMAND_TIME_EXCLUDE=()

source $ZSH/oh-my-zsh.sh

#ALIASES
alias b="doas make clean install"
alias cal="cal 2022"
alias ks="killall spotifyd"
alias fin="setxkbmap fi"
alias us="setxkbmap us"
alias ll="ls -lAgG"
alias xr="xrdb ~/.Xresources"
alias ka="killall"
alias ct="doas genlop -t"
alias clean="doas eclean distfiles && doas eclean packages"
alias repoadd="doas eselect repository enable"
alias repodis="doas eselect repository disable"
alias list="qlist -I"
alias dp="doas emerge --depclean -a"
alias bt="doas rc-service bluetooth start"
alias bs="doas rc-service bluetooth stop"
alias emerge="doas emerge --autounmask{,-write,-continue}"
alias dispatch-conf="doas dispatch-conf"
alias vpn="doas rc-service nordvpn start && sleep 1 && nordvpn c sweden"
alias movies="cd /mnt/games/movies"
alias rc-update="doas rc-update"
alias rc-service="doas rc-service"
alias useflags="doas vim /etc/portage/package.use"
alias mask="doas vim /etc/portage/package.mask"
alias glsa="doas glsa-check -f all"
alias ei="emerge --info"
alias make.conf="doas vim /etc/portage/make.conf"
alias kp="killall picom"
alias oldemerge="QUICKPKG_DEFAULT_OPTS="--include-config=y" emerge --ask --usepkgonly --quickpkg-direct=y --quickpkg-direct-root=/mnt/games/oldgentoo"
alias reboot="killall dwm & doas reboot"
alias poweroff="killall dwm && doas poweroff"
alias env="doas vim /etc/portage/package.env"
alias l="ls -lgG"
alias spotifyd="spotifyd --no-daemon & disown"
alias lll="ls -lAgG */*"
alias pass="base64 /dev/urandom | head -n 1"
alias s="du -sh *"
alias gc="git clone"
alias h="htop"
alias c="clear"
alias pp="sh ~/.config/picom.sh"
alias bb="doas make clean && doas make -j6 && doas make modules_install install && doas emerge @module-rebuild"
alias d="& disown"
alias lf="lfrun"
alias mtr="doas mount /dev/sdb1 /games"
alias neofetch="neofetch --ascii_distro gentoo_small"
alias defaults="doas vim /etc/portage/env/defaults"
alias stema="doas mount /dev/sdb1 & steam -console"
