PROMPT="%~ $(tput setaf 7)> "
CASE_SENSITIVE="false"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
plugins=(git web-search command-time zsh-syntax-highlighting zsh-interactive-cd zsh-autosuggestions zsh-navigation-tools history history-substring-search)
ZSH_COMMAND_TIME_MIN_SECONDS=1
ZSH_COMMAND_TIME_MSG="%s"
ZSH_COMMAND_TIME_COLOR="white"
ZSH_COMMAND_TIME_EXCLUDE=()

export ZSH="$HOME/.config/oh-my-zsh"
source $ZSH/oh-my-zsh.sh
unsetopt ALWAYS_LAST_PROMPT

#ALIASES
alias defaults="doas nvim /etc/portage/env/defaults"
alias keywords="doas nvim /etc/portage/package.accept_keywords"
alias ct="doas genlop -t"
alias clean="doas eclean distfiles && doas eclean packages"
alias repoadd="doas eselect repository enable"
alias repodis="doas eselect repository disable"
alias list="qlist -I"
alias dp="doas emerge --depclean -a"
alias emerge="doas emerge --autounmask{,-write,-continue}"
alias dispatch-conf="doas dispatch-conf"
alias rc-update="doas rc-update"
alias rc-service="doas rc-service"
alias useflags="doas nvim /etc/portage/package.use"
alias mask="doas nvim /etc/portage/package.mask"
alias glsa="doas glsa-check -f all"
alias ei="emerge --info"
alias es="doas emerge --sync"
alias make.conf="doas nvim /etc/portage/make.conf"
alias oldemerge="QUICKPKG_DEFAULT_OPTS="--include-config=y" emerge --ask --usepkgonly -
-quickpkg-direct=y --quickpkg-direct-root=/mnt/games/oldgentoo"
alias env="doas nvim /etc/portage/package.env"
alias b="doas make clean install"
alias cal="cal 2022"
alias ks="killall spotifyd"
alias fin="setxkbmap fi"
alias us="setxkbmap us"
alias xr="xrdb ~/.Xresources"
alias ka="killall"
alias bt="doas rc-service bluetooth start"
alias bs="doas rc-service bluetooth stop"
alias vpn="doas rc-service nordvpn start && sleep 1 && nordvpn c sweden"
alias movies="cd /mnt/games/movies"
alias kp="killall picom"
alias reboot="killall d & doas reboot"
alias poweroff="killall d & doas poweroff"
alias l="ls -lgGh "
alias spotifyd="spotifyd --no-daemon & disown"
alias lll="ls -lAgG */*"
alias pass="base64 /dev/urandom | head -n 1"
alias s="du -sh *"
alias gc="git clone"
alias c="clear"
alias pp="sh ~/.config/picom.sh"
alias bb="doas make clean && doas make -j6 && doas make modules_install install && doas emerge @module-rebuild && libnotify-notify-send kernel finished building && cd arch/x86/boot"
alias lf="lfrun"
alias mtr="doas mount /dev/sdb1 /games & doas mount /dev/nvme0n1p1 /efi"
alias virt-manager="doas rc-service libvirtd start && virt-manager"
alias t="tput reset"
alias h="btm -b"
alias unmask="doas nvim /etc/portage/package.unmask"
alias btm="btm -Tm"
alias steam="steam -console"
alias d="doas"
alias gp="git pull"
alias vim="nvim"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
