wireplumber.profiles = {
  main = {
    hardware.audio = required
  }
}

wireplumber.components = [
  {
    name = libpipewire-module-loopback
    type = pw-module
    arguments = {
      node.description  = "Vocaster One Stereo"
      capture.props = {
        node.name         = "vocaster-stereo"
        media.class       = "Audio/Sink"
        audio.rate        = 48000
        audio.channels    = 2
        audio.position    = "[ FL, FR ]"
      }
      playback.props = {
        node.name         = "vocaster-stereo-out"
        node.target       = "alsa_output.usb-Focusrite_Vocaster_One_USB_V1K5E3C2B09D98-00.pro-output-0"
        audio.position    = "[ AUX0, AUX1 ]"
        stream.dont-remix = true
        node.passive      = true
      }
    }
  }
]
