monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Focusrite_Vocaster_One_USB_V1K5E3C2B09D98-00"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
        api.alsa.rate = 48000
        audio.rate = 48000
        audio.channels = 2
        audio.position = "[ FL, FR ]"
      }
    }
  }
]
