context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Vocaster Stereo"
      capture.props = {
        node.name = "vocaster_stereo_in"
        audio.position = [ FL FR ]
        stream.dont-remix = true
        node.passive = true
      }
      playback.props = {
        node.name = "vocaster_stereo_out"
        node.target = "alsa_output.usb-Focusrite_Vocaster_One_USB_V1K5E3C2B09D98-00.pro-output-0"
        audio.position = [ FL FR ]
        audio.rate = 48000
        stream.dont-remix = true
      }
    }
  }
]
